### ISSUE TITLE
[Prompt]

### ISSUE THREAD

**Issue by Tractor1928** [rockbenben/ChatGPT-Shortcut#10]
### 提示词标题

code interpreter

### 提示词内容

I would like you to serve as a code interpreter, elucidate the syntax and the semantics of the code.

**Comment by rockbenben** [comment]
感谢分享，已更新到网站的 `IT/编程` 区块，并备注你的来源。下方为同步内容，有需要修改的话可回复。

title: '代码释义器',
content: 'I would like you to serve as a code interpreter, elucidate the syntax and the semantics of the code.',
content-cn: '我希望你能充当代码解释者，阐明代码的语法和语义。',
remark: '让 AI 解释每步代码的作用。来自 @Tractor1928 的投稿。',
