### ISSUE TITLE
[Bug]在搜索框输入中文时会被截断

### ISSUE THREAD

**Issue by zss2341** [rockbenben/ChatGPT-Shortcut#12]
### Checklist

- [X] 我已经看过 [使用说明](https://newzone.top/posts/2023-02-27-chatgpt_shortcuts.html)

### 问题描述

比如输入“翻译”时，会被截断为f。

### 补充说明

希望能够改进。

**Comment by rockbenben** [comment]
移动端支持中文输入，而 PC 端使用中文输入法会丢失焦点，需通过复制中文关键词来解决，或者使用浏览器自带的全文搜索功能。一般情况下，建议使用英文搜索。

Docusaurus 一直未修复，我会考虑增加搜索按钮还是重写个框架来修复问题。

https://github.com/rockbenben/ChatGPT-Shortcut#%E6%90%9C%E7%B4%A2%E6%97%A0%E6%B3%95%E8%BE%93%E5%85%A5%E4%B8%AD%E6%96%87

**Comment by rockbenben** [comment]
移动端搜索逻辑保持不变，而屏幕宽度阈值 768px 以上的 PC 端浏览引入 `debounce` 函数解决中文输入问题。但这在 PC 端产生两个问题：一是中文输入需在 800 毫秒内完成；二是 PC 端搜索刷新从即时变为 800 毫秒延迟。

若你有更好的解决方案，欢迎提供反馈。
