### ISSUE TITLE
[Bug]是否提供可以方便使用的csv或者json的prompts数据

### ISSUE THREAD

**Issue by WangRongsheng** [rockbenben/ChatGPT-Shortcut#16]
### Checklist

- [X] 我已经看过 [常见问题](https://newzone.top/posts/2023-02-27-chatgpt_shortcuts.html)

### 问题描述

是否提供可以方便使用的csv或者json的prompts数据

**Comment by rockbenben** [comment]
`users.tsx` 里有所有 prompts 数据，可以用它转换
