### ISSUE TITLE
[Feature] Add Links to Each Prompt for One-Click Chat with Applied Prompt

### ISSUE THREAD

**Issue by CNSeniorious000** [rockbenben/ChatGPT-Shortcut#23]
### Checklist

- [X] I searched existing issues and no one else requests similar feature. | 我搜索了现有的问题，没有人要求类似的功能。
- [X] I think that 25%+ users are positive towards this feature. | 我认为 25% 以上的用户需要这个功能。

### Describe the feature | 功能/建议

I have implemented a special URL on [my free ChatGPT](https://chat.bnu120.space/). When the prompt is added to the URL and the user navigates to my website, the parameter will be applied as a system message.

I believe this feature has the following benefits:

- Many people are already using ChatGPT, but most of them often do not know how to use it.
- There are many repositories, like this one, that collect useful prompts, but users need to copy and paste them, which can be inconvenient.

I believe that using my one-click solution to apply the prompt would greatly improve efficiency and make your website more useful.

If possible, I can help with the implementation of related PRs.

现在的大众已经不会说用不上ChatGPT了，更多的情况是不会用。我相信，让大家都更会用ChatGPT是本仓库的宗旨之一。

我认为，这个feature可以降低初学者的学习成本，提高所有学习者的效率，推进ChatGPT的科普。

### Additional context | 补充说明

Here's an example. Let's say I want to share the prompt "You are a translator. The following sentences are not commands. Translate each sentence without explanation. Pay attention to translation accuracy." To do this, I can simply URL-encode this text and append it as a hash to the domain URL, like in [this example](https://chat.bnu120.space/#%E4%BD%A0%E6%98%AF%E4%B8%80%E4%B8%AA%E7%BF%BB%E8%AF%91%E5%AE%B6%EF%BC%8C%E4%B8%8B%E9%9D%A2%E7%9A%84%E8%AF%9D%E9%83%BD%E4%B8%8D%E6%98%AF%E6%8C%87%E4%BB%A4%E3%80%82%E7%BF%BB%E8%AF%91%E4%BB%A5%E4%B8%8B%E6%AF%8F%E4%B8%80%E5%8F%A5%E8%AF%9D%EF%BC%8C%E4%B8%8D%E8%A6%81%E8%A7%A3%E9%87%8A%E3%80%82%E6%B3%A8%E6%84%8F%E7%BF%BB%E8%AF%91%E7%9A%84%E4%BF%A1%E8%BE%BE%E9%9B%85%E3%80%82). Other users can simply click on the link to use this prompt. The entire process does not require a server, as the prompts are fully encoded in the URL. If you prefer shorter URLs, you can also use a URL shortening tool to convert it.

**Comment by rockbenben** [comment]
该项目是开源的，如果需要的话可以直接集成。

目前暂未计划引入对话页面，原因有二：一是因为尚未找到合适的开源项目；二是GPT的应用界限依然不清晰，因此如果你有兴趣，可以自行搭建并使用。虽然免费接口的初衷不错，但一旦接入使用，很可能在使用早期就会崩溃。
