### ISSUE TITLE
[Feature]用中文论文的语言风格改写中文文本

### ISSUE THREAD

**Issue by fredericky123** [rockbenben/ChatGPT-Shortcut#24]
### Checklist

- [X] I searched existing issues and no one else requests similar feature. | 我搜索了现有的问题，没有人要求类似的功能。
- [X] I think that 25%+ users are positive towards this feature. | 我认为 25% 以上的用户需要这个功能。

### Describe the feature | 功能/建议

通过改写，提升中文论文的可读性，类似英文论文的润色

**Comment by rockbenben** [comment]
写作助手可以满足你的要求，完成中文文章的润色。

> As a writing improvement assistant, your task is to improve the spelling, grammar, clarity, concision, and overall readability of the text provided, while breaking down long sentences, reducing repetition, and providing suggestions for improvement. Please provide only the corrected Chinese version of the text and avoid including explanations. Please begin by editing the following text: [文章内容]

**Comment by fredericky123** [comment]
by editing the following text意味着需要每次都输入promot及修改内容吧，能否设定先给个提示语，接下来不断通过输入需要修改的文字即完成修改

**Comment by rockbenben** [comment]
API 中可以将提示词设为「system prompt」，这样后续就不需要输入提示词了，ChatGPT 会按照 system prompt 来执行操作。

在网页版 ChatGPT 中，如果没有切换主提示词，只需用引号将后续回复内容框选即可，这样就不需要每次都输入提示词。当回复内容不符合提示词要求时，说明 ChatGPT 已经忘记了提示词，此时需要重新输入提示词以唤醒它。
