### ISSUE TITLE
[Feature] Development plan 开发计划

### ISSUE THREAD

**Issue by rockbenben** [rockbenben/ChatGPT-Shortcut#25]
> Gathering features both in development and awaiting initiation.

## In Progress

- [x] User system refinement
    - [x] Google Auth
    - [x] Addition of personalized prompt words
    - [x] Removal of default favorite tags post-login
    - [x] Personal settings preservation upon login
    - [x] Online feedback interface
    - [x] Favored prompt words pinned at the top
    - [x] Personal prompt words modification
    - [x]  Comment system
- [x] Community Prompts
- [x] Discussion forum for prompt words
- [x] Assigning weights to prompt words and ranking them accordingly
- [x] Multi-language support enhancement (Japanese, Korean)
- [x] Extension support for Japanese and Korean languages

## Potential Additions

- [ ] Radical modification of existing prompt words #18
- [x] Conversational prompt submission #17

## Browser Extension
<a href="https://chrome.google.com/webstore/detail/chatgpt-shortcut/blcgeoojgdpodnmnhfpohphdhfncblnj"><img src="https://user-images.githubusercontent.com/3750161/214147732-c75e96a4-48a4-4b64-b407-c2402e899a75.PNG" height="40" alt="Chrome" valign="middle"></a> <a href="https://microsoftedge.microsoft.com/addons/detail/chatgpt-shortcut/hnggpalhfjmdhhmgfjpmhlfilnbmjoin"><img src="https://user-images.githubusercontent.com/3750161/233201810-d1026855-0482-44c8-b1ec-c7247134473e.png" height="40" alt="Edge" valign="middle"></a>

**Comment by HadlyGeuel** [comment]
destory a city
