### ISSUE TITLE
[Bug] 网站打不开了，即使翻墙后也不行。。。

### ISSUE THREAD

**Issue by Leptune** [rockbenben/ChatGPT-Shortcut#35]
### Checklist

- [X] I have searched [issues](https://github.com/rockbenben/ChatGPT-Shortcut/issues?q=)

### Describe the bug | 问题描述

如题

**Comment by rockbenben** [comment]
没有被墙的。关掉Wi-Fi，用手机直接连接试试看。

测试正常的。有可能是走了 Cloudflare 网络，我关掉Cloudflare节点看看你能不能正常连上

**Comment by Leptune** [comment]
用其他浏览器可以了，就是chrome一直不行。。。奇怪
