### ISSUE TITLE
[Feature] Want to set up a tracking script

### ISSUE THREAD

**Issue by B3nDan** [rockbenben/ChatGPT-Shortcut#43]
### Checklist

- [X] I searched existing issues and no one else requests similar feature. | 我搜索了现有的问题，没有人要求类似的功能。
- [X] I think that 25%+ users are positive towards this feature. | 我认为 25% 以上的用户需要这个功能。

### Describe the feature | 功能/建议

When I deploy this project myself, I need to see how many of my customers use this function.
So, I want to set up a tracking script, where can I set it ?

### Additional context | 补充说明

Not yet.

**Comment by rockbenben** [comment]
The tracking code is in `plugins\piwik.js`, and you can replace it with your own tracking script.
